### ISSUE TITLE
Command-line options?

### ISSUE THREAD

**Issue by jclarke0000** [libretro/mrboom-libretro#10]
I see in the old DOS version there were a number of command-line switches.  In particular, there is a switch to turn off monsters ( -M ).  Can I use a similar switch in the RetroArch version?  I'm running it with RetroPie, and I can't figure out where I might configure this.

Thanks!

**Comment by frranck** [comment]
Hi, @jclarke0000 right now you can't.
Which options interest you ?

**Comment by jclarke0000** [comment]
Awesome.  Thanks!  Looking forward to the update.

**Comment by frranck** [comment]
Added an option for the "no monsters" in current master!

**Comment by frranck** [comment]
Just added two team modes. I guess we can close this ?
